import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import { Navbar } from "@/components/Navbar/Navbar";
import MenuNavbar from "@/components/MenuNavbar/MenuNavbar";
import { Accordion } from 'flowbite-react';
import { Providers } from "@/Store/provider";
import Modal from "@/components/Modal/Modal";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <Navbar />
          <MenuNavbar />
          <Modal />
          {children}
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
