import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import { Navbar } from "@/components/Navbar/Navbar";
import MenuNavbar from "@/components/MenuNavbar/MenuNavbar";
import { Accordion } from 'flowbite-react';
import { Providers } from "@/Store/provider";
import Modal from "@/components/Modal/Modal";
import { fetchCategories } from "@/services/category-service";
import StorageOnLoad from "@/config/StorageOnLoad";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  //should add redis
  
  let mainCategories = [];
  try {
    const categories = await fetchCategories();
    mainCategories = categories.filter((item: any) => {
      console.log(item)
      return !item.parent_category;
    }); 

  }catch (err) {

  }

  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <StorageOnLoad 
            productCategories={mainCategories}
          />
          <Navbar />
          <MenuNavbar />
          <Modal />
          {children}
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
